# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import copy
import os
import warnings

import paddle
from paddlenlp.transformers import Qwen2Tokenizer
from PIL import Image

from paddlemix.models.llava.constants import DEFAULT_IMAGE_TOKEN, IMAGE_TOKEN_INDEX
from paddlemix.models.llava.conversation import conv_templates
from paddlemix.models.llava.language_model.llava_qwen import LlavaQwenForCausalLM
from paddlemix.models.llava.mm_utils import process_images
from paddlemix.models.llava.multimodal_encoder.siglip_encoder import (
    SigLipImageProcessor,
)
from paddlemix.models.llava.train_utils import tokenizer_image_token

warnings.filterwarnings("ignore")


class ImageSelector:
    def __init__(
        self,
        model_name="llava_qwen",
        pretrained="lmms-lab/llava-onevision-qwen2-7b-ov",
    ):

        self.model = LlavaQwenForCausalLM.from_pretrained(pretrained, image_aspect_ratio="pad", dtype="float16")
        self.tokenizer = Qwen2Tokenizer.from_pretrained(pretrained)
        self.image_processor = SigLipImageProcessor()
        self.model.eval()

    def orm(self, prompt, image_file):
        if not os.path.isfile(image_file) or not image_file.lower().endswith(("png", "jpg", "jpeg")):
            raise ValueError(f"Invalid image file: {image_file}")
        image = Image.open(image_file)
        image_tensor = process_images([image], self.image_processor, self.model.config)[0]
        image_tensor = image_tensor.cast(dtype="float16")
        question = f"{DEFAULT_IMAGE_TOKEN} This image is generated by a prompt: {prompt[0]}. Does this image accurately represent the prompt? Please answer yes or no without explanation."
        conv_template = "qwen_1_5"
        conv = copy.deepcopy(conv_templates[conv_template])
        conv.append_message(conv.roles[0], question)
        conv.append_message(conv.roles[1], None)
        prompt_question = conv.get_prompt()
        input_ids = tokenizer_image_token(
            prompt_question, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pd"
        ).unsqueeze(0)

        image_size = image.size
        succeed = False
        max_retries = 1
        retry_count = 0

        while not succeed and retry_count < max_retries:
            retry_count += 1
            with paddle.no_grad():
                cont = self.model.generate(
                    input_ids,
                    images=[image_tensor],
                    image_sizes=[image_size],
                    decode_strategy="sampling",
                    temperature=1.0,
                    max_new_tokens=100,
                    top_p=0.8,
                    top_k=20,
                    repetition_penalty=1.05,
                    return_dict_in_generate=True,
                )

            cur_reponse = self.tokenizer.batch_decode(cont[0], skip_special_tokens=True)[0].lower()
            if cur_reponse not in ["yes", "no"]:
                break
            else:
                succeed = True

            scores = paddle.concat(x=[score.unsqueeze(axis=1) for score in cont[1]], axis=1)

            yes_prob = scores.item()

        if not succeed:
            print("Failed to generate a valid 'yes' or 'no' answer after maximum retries. Reponse:" + cur_reponse)
            return False, 0.0
        return cur_reponse == "yes", yes_prob

    def parm(self, prompt, image_file, clear):
        if not os.path.isfile(image_file) or not image_file.lower().endswith(("png", "jpg", "jpeg")):
            raise ValueError(f"Invalid image file: {image_file}")
        image = Image.open(image_file)
        image_tensor = process_images([image], self.image_processor, self.model.config)[0]
        image_tensor = image_tensor.cast(dtype="float16")
        if not clear and self.clarity_judgement(prompt, image_tensor, image) == "no":
            return False, 1.0, False
        else:
            potential, no_prob = self.potential_assessment(prompt, image_tensor, image)
            return potential, no_prob, True

    def clarity_judgement(self, prompt, image_tensor, image):
        question = f"{DEFAULT_IMAGE_TOKEN} This image is a certain step in the text-to-image generation process with a prompt: {prompt[0]}. It is not the final generated one, and will keep iterating better. Do you think this image can be used to judge whether it has the potential to iterate to the image satisfied the prompt? (The image, which needn't to be confused but can be clear and basically judged the object, can be used to judge the potential) Answer yes or no without explanation."
        question = f"""{DEFAULT_IMAGE_TOKEN} \n The above image is a certain step  in the text to image generation process. This image is not the final generated one, and will keep iterating better. The image is generated by prompt '{prompt[0]}.'
        Do you think this image can be used to judge whether it has the potential to iterate to the image satisfied the prompt?(The image, which needn't to be confused  but can be clear and basically judged the object, can be used to judge the potential)
        Answer yes or no with no explanation.(yes or no in lowercase and no full point)"""
        conv_template = "qwen_1_5"
        conv = copy.deepcopy(conv_templates[conv_template])
        conv.append_message(conv.roles[0], question)
        conv.append_message(conv.roles[1], None)
        prompt_question = conv.get_prompt()

        input_ids = tokenizer_image_token(
            prompt_question, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pd"
        ).unsqueeze(0)

        image_size = image.size
        succeed = False
        max_retries = 1
        retry_count = 0

        while not succeed and retry_count < max_retries:
            retry_count += 1
            with paddle.no_grad():
                cont = self.model.generate(
                    input_ids,
                    images=[image_tensor],
                    image_sizes=[image_size],
                    decode_strategy="sampling",
                    temperature=1.0,
                    max_new_tokens=100,
                    top_p=0.8,
                    top_k=20,
                    repetition_penalty=1.05,
                    return_dict_in_generate=True,
                )

            cur_reponse = self.tokenizer.batch_decode(cont[0], skip_special_tokens=True)[0].lower()
            if cur_reponse not in ["yes", "no"]:
                break
            else:
                succeed = True

        if not succeed:
            print("Failed to generate a valid 'yes' or 'no' answer after maximum retries.")
        return cur_reponse

    def potential_assessment(self, prompt, image_tensor, image):
        clear_question = f"""{DEFAULT_IMAGE_TOKEN} The above image is a certain step  in the text to image generation process. This image is not the final generated one, and will keep iterating better. The image is generated by prompt '{prompt[0]}.'
        Do you think this image can be used to judge whether it has the potential to iterate to the image satisfied the prompt?(The image, which needn't to be confused  but can be clear and basically judged the object, can be used to judge the potential)
        Answer yes or no with no explanation.(yes or no in lowercase and no full point)"""
        question = f"{DEFAULT_IMAGE_TOKEN} Do you think whether the image has the potential to iterate to the image satisfied the prompt? Please answer yes or no without explanation."
        question = "Do you think whether the image has the potential to iterate to the image satisfied the prompt? Please answer yes or no with no explanation.(yes or no in lowercase and no full point)"
        conv_template = "qwen_1_5"
        conv = copy.deepcopy(conv_templates[conv_template])
        conv.append_message(conv.roles[0], clear_question)
        conv.append_message(conv.roles[1], "yes")
        conv.append_message(conv.roles[0], question)
        conv.append_message(conv.roles[1], None)
        prompt_question = conv.get_prompt()
        input_ids = tokenizer_image_token(
            prompt_question, self.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pd"
        ).unsqueeze(0)
        image_size = image.size
        succeed = False
        max_retries = 1
        retry_count = 0

        while not succeed and retry_count < max_retries:
            retry_count += 1
            with paddle.no_grad():
                cont = self.model.generate(
                    input_ids,
                    images=[image_tensor],
                    image_sizes=[image_size],
                    decode_strategy="sampling",
                    temperature=1.0,
                    max_new_tokens=100,
                    top_p=0.8,
                    top_k=20,
                    repetition_penalty=1.05,
                    return_dict_in_generate=True,
                )

            cur_reponse = self.tokenizer.batch_decode(cont[0], skip_special_tokens=True)[0].lower()
            if cur_reponse not in ["yes", "no"]:
                break
            else:
                succeed = True
            scores = paddle.concat(x=[score.unsqueeze(axis=1) for score in cont[1]], axis=1)

            no_prob = scores.item()

        if not succeed:
            print("Failed to generate a valid 'yes' or 'no' answer after maximum retries.")
            return False, 50.0
        return "yes" in cur_reponse, no_prob
